language: python
sudo: false
python:
  - "2.7"

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#install-linux
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
 
script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "046f1b5dae10"
  - COMMIT_AUTHOR_EMAIL: "public-audio@w3.org"